module.exports = { abi: 
   [ { constant: true,
       inputs: [ { name: '_key', type: 'bytes32' } ],
       name: 'getKey',
       outputs: 
        [ { name: 'purposes', type: 'uint256[]' },
          { name: 'keyType', type: 'uint256' },
          { name: 'key', type: 'bytes32' } ],
       payable: false,
       stateMutability: 'view',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_key', type: 'bytes32' },
          { name: '_purpose', type: 'uint256' },
          { name: '_keyType', type: 'uint256' } ],
       name: 'addKey',
       outputs: [ { name: 'success', type: 'bool' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: false,
       inputs: [ { name: '_claimId', type: 'bytes32' } ],
       name: 'removeClaim',
       outputs: [ { name: 'success', type: 'bool' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_key', type: 'bytes32' },
          { name: '_purpose', type: 'uint256' } ],
       name: 'removeKey',
       outputs: [ { name: 'success', type: 'bool' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_id', type: 'uint256' },
          { name: '_approve', type: 'bool' } ],
       name: 'approve',
       outputs: [ { name: 'success', type: 'bool' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: true,
       inputs: [ { name: '_topic', type: 'uint256' } ],
       name: 'getClaimIdsByTopic',
       outputs: [ { name: 'claimIds', type: 'bytes32[]' } ],
       payable: false,
       stateMutability: 'view',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_topic', type: 'uint256' },
          { name: '_scheme', type: 'uint256' },
          { name: '_issuer', type: 'address' },
          { name: '_signature', type: 'bytes' },
          { name: '_data', type: 'bytes' },
          { name: '_uri', type: 'string' } ],
       name: 'addClaim',
       outputs: [ { name: 'claimRequestId', type: 'uint256' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_to', type: 'address' },
          { name: '_value', type: 'uint256' },
          { name: '_data', type: 'bytes' } ],
       name: 'execute',
       outputs: [ { name: 'executionId', type: 'uint256' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: true,
       inputs: [ { name: '_claimId', type: 'bytes32' } ],
       name: 'getClaim',
       outputs: 
        [ { name: 'topic', type: 'uint256' },
          { name: 'scheme', type: 'uint256' },
          { name: 'issuer', type: 'address' },
          { name: 'signature', type: 'bytes' },
          { name: 'data', type: 'bytes' },
          { name: 'uri', type: 'string' } ],
       payable: false,
       stateMutability: 'view',
       type: 'function' },
     { constant: false,
       inputs: 
        [ { name: '_claimId', type: 'bytes32' },
          { name: '_topic', type: 'uint256' },
          { name: '_scheme', type: 'uint256' },
          { name: '_issuer', type: 'address' },
          { name: '_signature', type: 'bytes' },
          { name: '_data', type: 'bytes' },
          { name: '_uri', type: 'string' } ],
       name: 'changeClaim',
       outputs: [ { name: 'success', type: 'bool' } ],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'function' },
     { constant: true,
       inputs: [ { name: '_purpose', type: 'uint256' } ],
       name: 'keysByPurpose',
       outputs: [ { name: 'keys', type: 'bytes32[]' } ],
       payable: false,
       stateMutability: 'view',
       type: 'function' },
     { inputs: [],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'constructor' },
     { payable: true, stateMutability: 'payable', type: 'fallback' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'key', type: 'bytes32' },
          { indexed: true, name: 'purpose', type: 'uint256' },
          { indexed: true, name: 'keyType', type: 'uint256' } ],
       name: 'KeyAdded',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'key', type: 'bytes32' },
          { indexed: true, name: 'purpose', type: 'uint256' },
          { indexed: true, name: 'keyType', type: 'uint256' } ],
       name: 'KeyRemoved',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'executionId', type: 'uint256' },
          { indexed: true, name: 'to', type: 'address' },
          { indexed: true, name: 'value', type: 'uint256' },
          { indexed: false, name: 'data', type: 'bytes' } ],
       name: 'ExecutionRequested',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'executionId', type: 'uint256' },
          { indexed: true, name: 'to', type: 'address' },
          { indexed: true, name: 'value', type: 'uint256' },
          { indexed: false, name: 'data', type: 'bytes' } ],
       name: 'Executed',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'executionId', type: 'uint256' },
          { indexed: false, name: 'approved', type: 'bool' } ],
       name: 'Approved',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'claimRequestId', type: 'uint256' },
          { indexed: true, name: 'topic', type: 'uint256' },
          { indexed: false, name: 'scheme', type: 'uint256' },
          { indexed: true, name: 'issuer', type: 'address' },
          { indexed: false, name: 'signature', type: 'bytes' },
          { indexed: false, name: 'data', type: 'bytes' },
          { indexed: false, name: 'uri', type: 'string' } ],
       name: 'ClaimRequested',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'claimId', type: 'bytes32' },
          { indexed: true, name: 'topic', type: 'uint256' },
          { indexed: false, name: 'scheme', type: 'uint256' },
          { indexed: true, name: 'issuer', type: 'address' },
          { indexed: false, name: 'signature', type: 'bytes' },
          { indexed: false, name: 'data', type: 'bytes' },
          { indexed: false, name: 'uri', type: 'string' } ],
       name: 'ClaimAdded',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'claimId', type: 'bytes32' },
          { indexed: true, name: 'topic', type: 'uint256' },
          { indexed: false, name: 'scheme', type: 'uint256' },
          { indexed: true, name: 'issuer', type: 'address' },
          { indexed: false, name: 'signature', type: 'bytes' },
          { indexed: false, name: 'data', type: 'bytes' },
          { indexed: false, name: 'uri', type: 'string' } ],
       name: 'ClaimRemoved',
       type: 'event' },
     { anonymous: false,
       inputs: 
        [ { indexed: true, name: 'claimId', type: 'bytes32' },
          { indexed: true, name: 'topic', type: 'uint256' },
          { indexed: false, name: 'scheme', type: 'uint256' },
          { indexed: true, name: 'issuer', type: 'address' },
          { indexed: false, name: 'signature', type: 'bytes' },
          { indexed: false, name: 'data', type: 'bytes' },
          { indexed: false, name: 'uri', type: 'string' } ],
       name: 'ClaimChanged',
       type: 'event' } ],
  bin: '' }